# Generated by Django 5.0.2 on 2024-02-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=14, unique=True)),
                ('title', models.CharField()),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('review_text', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorsBooks',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.authors')),
            ],
            options={
                'db_table': 'authors_books',
                'managed': False,
            },
        ),
    ]
